name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action to perform (plan, apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
      resource_scope:
        description: 'Choose whether to run the action on all resources or custom resources'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - custom
      target_resource:
        description: 'Comma-separated DynamoDB table names (e.g., table1,table2) or AWS resources (e.g., aws_instance.my_instance,aws_s3_bucket.my_bucket). Only applicable if custom is selected.'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      # Plan Step: Conditional logic based on resource scope (all or custom)
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          if [ "${{ github.event.inputs.resource_scope }}" == "all" ]; then
            echo "Running plan for all resources"
            terraform plan
          elif [ "${{ github.event.inputs.resource_scope }}" == "custom" ] && [ "${{ github.event.inputs.target_resource }}" != "" ]; then
            # Split the target_resource string into an array by commas
            IFS=',' read -r -a resources <<< "${{ github.event.inputs.target_resource }}"
            
            # Loop over each resource and run the appropriate command
            for resource in "${resources[@]}"; do
              if [[ "$resource" == *.* ]]; then
                echo "Running plan for AWS resource: $resource"
                terraform plan --target=$resource
              else
                echo "Running plan for DynamoDB table: $resource"
                terraform plan --target="aws_dynamodb_table.dynamodb_tables[\"$resource\"]"
              fi
            done
          else
            echo "No valid target resource provided."
            exit 1
          fi

      # Apply Step: Conditional logic based on resource scope (all or custom)
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          if [ "${{ github.event.inputs.resource_scope }}" == "all" ]; then
            echo "Running apply for all resources"
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.resource_scope }}" == "custom" ] && [ "${{ github.event.inputs.target_resource }}" != "" ]; then
            # Split the target_resource string into an array by commas
            IFS=',' read -r -a resources <<< "${{ github.event.inputs.target_resource }}"
            
            # Loop over each resource and run the appropriate command
            for resource in "${resources[@]}"; do
              if [[ "$resource" == *.* ]]; then
                echo "Running apply for AWS resource: $resource"
                terraform apply --target=$resource -auto-approve
              else
                echo "Running apply for DynamoDB table: $resource"
                terraform apply --target="aws_dynamodb_table.dynamodb_tables[\"$resource\"]" -auto-approve
              fi
            done
          else
            echo "No valid target resource provided."
            exit 1
          fi
