name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action to perform (plan, apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
      target_resource:
        description: 'Target resource (prefix DynamoDB tables with dynamodb:, e.g., dynamodb:table1 or aws_instance.my_instance for EC2)'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      # Determine the target format based on the resource type (DynamoDB table or other resources)
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          if [[ "${{ github.event.inputs.target_resource }}" == dynamodb:* ]]; then
            table_name=${{ github.event.inputs.target_resource#"dynamodb:" }}
            terraform plan --target='aws_dynamodb_table.dynamodb_tables["'$table_name'"]'
          elif [ "${{ github.event.inputs.target_resource }}" != "" ]; then
            terraform plan --target=${{ github.event.inputs.target_resource }}
          else
            terraform plan
          fi

      # Terraform Apply with correct syntax for DynamoDB tables and other resources
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          if [[ "${{ github.event.inputs.target_resource }}" == dynamodb:* ]]; then
            table_name=${{ github.event.inputs.target_resource#"dynamodb:" }}
            terraform apply --target='aws_dynamodb_table.dynamodb_tables["'$table_name'"]' -auto-approve
          elif [ "${{ github.event.inputs.target_resource }}" != "" ]; then
            terraform apply --target=${{ github.event.inputs.target_resource }} -auto-approve
          else
            terraform apply -auto-approve
          fi
